### ISSUE TITLE
Missing umapIgraphClusters function

### ISSUE THREAD

**Issue by emmafjones** [caleblareau/mtscATACpaper_reproducibility#4]
Hi there,

I'm going through the reproducibility code to recreate the CLL figure to better understand the analyses done in the mtscATACseq paper. I could not find where this function is coming from and am getting an error that it does not exist. Have I missed this function from another script?

https://github.com/caleblareau/mtscATACpaper_reproducibility/blob/e543610bf29dbac1094994c54d3e7edd41609d5a/figure_CLL/code/12_LSI_embedding.R#L241

**Comment by caleblareau** [comment]
Hmm... you know, I'm not sure either. I searched my computer and I couldn't find it. It looks like a relic of some other script... I apologize for this. 

The function is simply clustering the data; I think that I did it in UMAP space to make it look pretty, but you can sub this out for whatever clustering approach (e.g. Seurat) that is convenient

I'll also note that this script is a bit of a relic already from the Greenleaf lab's MPAL paper (https://github.com/GreenleafLab/MPAL-Single-Cell-2019) which has since been supplanted by the ArchR package. I wouldn't recommend spending too much time on this script relative to using the tools now in ArchR / Signac.

**Comment by emmafjones** [comment]
Ok, I'll focus on looking at the newer tools. Thanks!
